-- Washington Hot Springs — D1 Seed Data
-- Generated by scripts/seed-d1.mjs on 2026-03-25T23:31:16.461Z

DELETE FROM conditions;
DELETE FROM springs;

INSERT INTO springs (id, slug, name, lat, lng, gps, temp_f, fee, fee_notes, description, access_type, hours, season, clothing, cell_coverage, road_condition, parking, best_time, avoid_when, insider_tips, nearby_gems, last_verified, maintenance_day, alerts) VALUES ('51a51c9b-fbd2-4207-92ea-e9a5e5640f24', 'sol-duc', 'Sol Duc Hot Springs', 47.9689, -123.8631, '47.9689° N, 123.8631° W', 78, 18, 'Cash only, no ATM nearby', 'Olympic Hot Springs in Olympic National Park', 'drive-up', '9 AM - 8 PM', 'year-round', 'required', 'Verizon: 1 bar, AT&T: none', 'Paved, narrow last 2 miles', 'Lot fills by 11 AM weekends', 'Weekday mornings before 10 AM', 'Holiday weekends', 'The third pool from the entrance is the warmest and least crowded. Bring water shoes as the rocks can be slippery. If you''re here during heavy rain, check the river level - it can flood the lower pools.', 'Hike to Sol Duc Falls (1.6 miles), Appleton Pass trail for wildflowers in July, Fairy Lake for photography', '2024-01-15', 'Closed first Tuesday of each month', 'No current alerts - all pools open');
