/**
 * Hugo Markdown → Cloudflare D1 Seed Script
 *
 * Reads all spring markdown files from the Hugo site and generates:
 *   db/seed.sql — INSERT statements for D1
 *
 * Usage (generate SQL):
 *   node scripts/seed-d1.mjs
 *
 * Usage (apply to local D1):
 *   node scripts/seed-d1.mjs && wrangler d1 execute wa-hot-springs --local --file=db/seed.sql
 *
 * Usage (apply to remote D1):
 *   node scripts/seed-d1.mjs && wrangler d1 execute wa-hot-springs --file=db/seed.sql
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import crypto from 'crypto';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const HUGO_SPRINGS = path.join(ROOT, '../wa-springs-directory/content/springs');
const OUT_SQL = path.join(ROOT, 'db/seed.sql');

// ─── Parse YAML frontmatter ───────────────────────────────────────────────────
function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};

  const yaml = match[1];
  const result = {};

  for (const line of yaml.split('\n')) {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;

    const key = line.slice(0, colonIdx).trim();
    let value = line.slice(colonIdx + 1).trim();

    // Strip surrounding quotes
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    // Coerce numbers
    if (value !== '' && !isNaN(Number(value))) {
      result[key] = Number(value);
    } else {
      result[key] = value;
    }
  }

  return result;
}

// ─── Parse GPS string → { lat, lng } ─────────────────────────────────────────
function parseGPS(gpsStr) {
  if (!gpsStr) return { lat: null, lng: null };

  // "47.9689° N, 123.8631° W" or "47.9689, -123.8631"
  const clean = gpsStr.replace(/°/g, '').trim();

  const dmsMatch = clean.match(
    /(-?\d+\.?\d*)\s*[NS]?,?\s*(-?\d+\.?\d*)\s*[EW]?/i
  );
  if (!dmsMatch) return { lat: null, lng: null };

  let lat = parseFloat(dmsMatch[1]);
  let lng = parseFloat(dmsMatch[2]);

  // Western longitudes are negative; if value is positive and W is indicated, negate
  if (/W/i.test(clean) && lng > 0) lng = -lng;

  return { lat, lng };
}

// ─── SQL escape ───────────────────────────────────────────────────────────────
function sql(value) {
  if (value === null || value === undefined || value === '') return 'NULL';
  if (typeof value === 'number') return value.toString();
  return `'${String(value).replace(/'/g, "''")}'`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────
const files = fs.readdirSync(HUGO_SPRINGS)
  .filter(f => f.endsWith('.md') && f !== '_index.md');

if (files.length === 0) {
  console.warn('⚠️  No spring markdown files found — adding placeholder data.');
}

console.log(`\n📂 Found ${files.length} spring file(s) in Hugo content\n`);

const statements = [
  '-- Washington Hot Springs — D1 Seed Data',
  `-- Generated by scripts/seed-d1.mjs on ${new Date().toISOString()}`,
  '',
  'DELETE FROM conditions;',
  'DELETE FROM springs;',
  '',
];

for (const file of files) {
  const slug = file.replace('.md', '');
  const content = fs.readFileSync(path.join(HUGO_SPRINGS, file), 'utf-8');
  const fm = parseFrontmatter(content);
  const { lat, lng } = parseGPS(fm.gps || '');
  const id = crypto.randomUUID();

  statements.push(
    `INSERT INTO springs (id, slug, name, lat, lng, gps, temp_f, fee, fee_notes, description, ` +
    `access_type, hours, season, clothing, cell_coverage, road_condition, parking, ` +
    `best_time, avoid_when, insider_tips, nearby_gems, last_verified, maintenance_day, alerts) VALUES (` +
    `${sql(id)}, ${sql(slug)}, ${sql(fm.title || fm.name || slug)}, ` +
    `${sql(lat)}, ${sql(lng)}, ${sql(fm.gps)}, ` +
    `${sql(fm.temp_f)}, ${sql(fm.fee)}, ${sql(fm.fee_notes)}, ` +
    `${sql(fm.description)}, ${sql(fm.access_type)}, ${sql(fm.hours)}, ` +
    `${sql(fm.season)}, ${sql(fm.clothing)}, ${sql(fm.cell_coverage)}, ` +
    `${sql(fm.road_condition)}, ${sql(fm.parking)}, ` +
    `${sql(fm.best_time)}, ${sql(fm.avoid_when)}, ${sql(fm.insider_tips)}, ` +
    `${sql(fm.nearby_gems)}, ${sql(fm.last_verified)}, ` +
    `${sql(fm.maintenance_day)}, ${sql(fm.alerts)}` +
    `);`
  );

  console.log(`  ✅ ${slug} (${lat ?? '?'}, ${lng ?? '?'})`);
}

// ─── Placeholder springs (real data to be added via Keystatic or wrangler) ────
// If no Hugo markdown springs exist yet, seed a minimal placeholder so the
// map and trip planner have something to render during development.
if (files.length === 0) {
  const placeholders = [
    { slug: 'sol-duc-hot-springs', name: 'Sol Duc Hot Springs', lat: 47.9689, lng: -123.8631, temp_f: 98, fee: 18, access_type: 'drive-up', season: 'seasonal' },
    { slug: 'olympic-hot-springs', name: 'Olympic Hot Springs', lat: 47.9742, lng: -123.7383, temp_f: 95, fee: 0, access_type: 'hike-in', season: 'year-round' },
    { slug: 'goldmyer-hot-springs', name: 'Goldmyer Hot Springs', lat: 47.4833, lng: -121.4194, temp_f: 113, fee: 15, access_type: 'hike-in', season: 'year-round' },
    { slug: 'baker-hot-springs', name: 'Baker Hot Springs', lat: 48.7280, lng: -121.6830, temp_f: 105, fee: 0, access_type: 'drive-up', season: 'year-round' },
    { slug: 'gamma-hot-springs', name: 'Gamma Hot Springs', lat: 48.1330, lng: -121.1450, temp_f: 100, fee: 0, access_type: 'hike-in', season: 'summer' },
    { slug: 'ohanapecosh-hot-springs', name: 'Ohanapecosh Hot Springs', lat: 46.7302, lng: -121.5678, temp_f: 84, fee: 0, access_type: 'hike-in', season: 'year-round' },
  ];

  for (const p of placeholders) {
    const id = crypto.randomUUID();
    statements.push(
      `INSERT INTO springs (id, slug, name, lat, lng, temp_f, fee, access_type, season) VALUES (` +
      `${sql(id)}, ${sql(p.slug)}, ${sql(p.name)}, ${p.lat}, ${p.lng}, ` +
      `${sql(p.temp_f)}, ${sql(p.fee)}, ${sql(p.access_type)}, ${sql(p.season)}` +
      `);`
    );
    console.log(`  📍 placeholder: ${p.slug}`);
  }
}

statements.push('');

fs.writeFileSync(OUT_SQL, statements.join('\n'), 'utf-8');

console.log(`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅  Seed SQL written → db/seed.sql

To apply locally:
  wrangler d1 execute wa-hot-springs --local --file=db/schema.sql
  wrangler d1 execute wa-hot-springs --local --file=db/seed.sql

To apply to production (after wrangler d1 create wa-hot-springs):
  wrangler d1 execute wa-hot-springs --file=db/schema.sql
  wrangler d1 execute wa-hot-springs --file=db/seed.sql
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`);
